In [22]:
import os
import re
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [23]:
directory_path = 'C:\\Users\\tech\\Desktop\\MoroccoEconomyYTAnalysis\\data\\raw' 
all_subtitles = []

for filename in os.listdir(directory_path):
    if filename.endswith('.txt'):
        with open(os.path.join(directory_path, filename), 'r', encoding='utf-8') as f:
            content = f.read()
            all_subtitles.append(content)

df = pd.DataFrame(all_subtitles, columns=['subtitles'])
df.head()  # Display the first few rows to inspect your data

                                           subtitles
0  madame monsieur bonsoir les marocains\n\nrésid...
1  prépondérant dans l'économie le système\n\nban...
2  [Musique]\n\nbon\n\n[Musique]\n\nmais messieur...
3  en tout\n\nbonsoir à toutes et à tous et rende...
4  [Musique]\n\nmerci tout d'abord d'avoir répond...

In [24]:
def remove_music(text):
    return re.sub(r'\[Musique\]', '', text)  

df['subtitles'] = df['subtitles'].apply(remove_music)
df.head()

                                           subtitles
0  madame monsieur bonsoir les marocains\n\nrésid...
1  prépondérant dans l'économie le système\n\nban...
2  \n\nbon\n\n\n\nmais messieurs bonsoir et bienv...
3  en tout\n\nbonsoir à toutes et à tous et rende...
4  \n\nmerci tout d'abord d'avoir répondu à\n\nno...

In [25]:
def remove_newlines(text):
    return re.sub(r'\n', ' ', text)  # replacing with space to keep words separate

df['subtitles'] = df['subtitles'].apply(remove_newlines)
df.head()

                                           subtitles
0  madame monsieur bonsoir les marocains  résiden...
1  prépondérant dans l'économie le système  banca...
2    bon    mais messieurs bonsoir et bienvenue d...
3  en tout  bonsoir à toutes et à tous et rendez ...
4    merci tout d'abord d'avoir répondu à  notre ...

In [26]:
df['subtitles'] = df['subtitles'].str.lower()
df.head()

                                           subtitles
0  madame monsieur bonsoir les marocains  résiden...
1  prépondérant dans l'économie le système  banca...
2    bon    mais messieurs bonsoir et bienvenue d...
3  en tout  bonsoir à toutes et à tous et rendez ...
4    merci tout d'abord d'avoir répondu à  notre ...

In [27]:
def remove_punctuation(text):
    # This regex keeps French alphabets, spaces, and French special characters
    return re.sub(r'[^a-zàâçéèêëîïôûùüÿæœ\s]', '', text)

df['subtitles'] = df['subtitles'].apply(remove_punctuation)
df.head()

                                           subtitles
0  madame monsieur bonsoir les marocains  résiden...
1  prépondérant dans léconomie le système  bancai...
2    bon    mais messieurs bonsoir et bienvenue d...
3  en tout  bonsoir à toutes et à tous et rendez ...
4    merci tout dabord davoir répondu à  notre ap...

In [28]:
nltk.download('punkt')  

df['tokens'] = df['subtitles'].apply(word_tokenize)
df.head()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\tech\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,subtitles,tokens
0,madame monsieur bonsoir les marocains résiden...,"[madame, monsieur, bonsoir, les, marocains, ré..."
1,prépondérant dans léconomie le système bancai...,"[prépondérant, dans, léconomie, le, système, b..."
2,bon mais messieurs bonsoir et bienvenue d...,"[bon, mais, messieurs, bonsoir, et, bienvenue,..."
3,en tout bonsoir à toutes et à tous et rendez ...,"[en, tout, bonsoir, à, toutes, et, à, tous, et..."
4,merci tout dabord davoir répondu à notre ap...,"[merci, tout, dabord, davoir, répondu, à, notr..."

In [29]:
nltk.download('stopwords')
stop_words = set(stopwords.words('french'))  # Now using French stopwords

df['tokens'] = df['tokens'].apply(lambda x: [word for word in x if word not in stop_words])
df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tech\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,subtitles,tokens
0,madame monsieur bonsoir les marocains résiden...,"[madame, monsieur, bonsoir, marocains, résiden..."
1,prépondérant dans léconomie le système bancai...,"[prépondérant, léconomie, système, bancaire, m..."
2,bon mais messieurs bonsoir et bienvenue d...,"[bon, messieurs, bonsoir, bienvenue, minutes, ..."
3,en tout bonsoir à toutes et à tous et rendez ...,"[tout, bonsoir, toutes, tous, rendez, retrouve..."
4,merci tout dabord davoir répondu à notre ap...,"[merci, tout, dabord, davoir, répondu, appel, ..."

In [30]:
def split_into_sentences(text):
    # Divise le texte en phrases en utilisant des points, des points d'interrogation et des points d'exclamation comme délimiteurs
    sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', text)
    return sentences

In [17]:
# Appliquer la fonction de division aux sous-titres et créer un nouveau dataframe
new_rows = []
for index, row in df.iterrows():
    sentences = split_into_sentences(row['subtitles'])
    for sentence in sentences:
        new_rows.append({ 'subtitles': sentence, 'token': row['tokens']})

df_expanded = pd.DataFrame(new_rows)

In [19]:
df.to_csv('cleaned_dataset.csv', index=False, encoding=utf)

In [20]:
print(df_expanded)

                                            subtitles
0   madame monsieur bonsoir les marocains  résiden...  \
1   prépondérant dans léconomie le système  bancai...
2     bon    mais messieurs bonsoir et bienvenue d...
3   en tout  bonsoir à toutes et à tous et rendez ...
4     merci tout dabord davoir répondu à  notre ap...
5   bienvenue dans le journal de  lintelligence éc...
6     bienvenue sur projet du maroc la chaîne  qui...
7     bonjour tout le monde et bienvenue à  urgent...
8   comment le maroc estil devenu la e  puissance ...
9     bonjour tout le monde et bienvenue à  urgenc...
10    bonjour à tous et bienvenue sur projet  du m...
11    bonsoir à tous bienvenue dans linvité  de la...
12  applaudissements  alors nous avons eu le plais...
13  cette émission vous est présentée par  thème w...
14  bien bonjour à toutes et à tous jespère  que v...
15  bonjour à toutes et à tous et bienvenue  dans ...
16  madame monsieur bonsoir au menu de  questions ...
17  la crise en ukraine a causé pour la  première ...
18  comme partout ailleurs dans le monde les  entr...
19  cette émission vous est présentée par  thème w...
20  les rapports de bakel maghreb sur la sur  les ...
21  si la limite le dit textuellement que  linstru...
22  si la limite le dit textuellement que  linstru...
23  lenvironnement actuel est caractérisé  par  on...
24    les investissements directs étrangers en  pl...
25  voilà monsieur bonsoir au menu deux  questions...
26    lafrique au point de vue de  lintelligence é...
27  un enchaînement de projets économiques  unis p...
28  malgré le renchérissement des prix des  matièr...
29    bonsoir et bienvenue dans linvité de la  réd...
30  situé entre le bassin méditerranéen et  locéan...
31    à la fin des années  du siècle dernier  lanc...
32    lannée  sannonce  économiquement difficile  ...
33    avec ses deux façades maritimes sans  littor...
34  tuation économique marocaine avec vous  vicky ...
35  le taux dinflation annuel au maroc a  bondit à...
36  grâce aux phosphate on fabrique ce quon  appel...
37  on a réussi à choisir casablanca au  maroc pou...
38  en suisse et je meurs ils ont  dispositif écon...
39  bonjour à tous je vous propose  aujourdhui une...
40  bienvenue dans le journal de  lintelligence éc...
41    bonjour tout le monde et bienvenue à  urgenc...
42  parmi les institutions qui contribuent  au dév...
43    bonjour tout le monde et bienvenue à  urgenc...
44    au maroc est resté dans lordre de  grandeur ...
45    cette conférence sur la diplomatie  économiq...
46    bienvenue sur la chaîne projet du maroc  auj...
47    bienvenue sur la chaîne projet du maroc  auj...
48  cette émission vous est présenté par la  caiss...
49    bonjour bonjour alors vous êtes expert  dans...
50    bonjour et bienvenue à urgence  économique a...
51    bienvenue sur la chaîne projet du maroc  nou...
52  cette émission vous est présentée par  thème w...
53    salam à tous et bienvenue sur maroc   noubli...
54    salam à tous et bienvenue sur maroc   noubli...
55  donc en résumé pour lannée qui vient de  sécou...

                                                token
0   [madame, monsieur, bonsoir, marocains, résiden...
1   [prépondérant, léconomie, système, bancaire, m...
2   [bon, messieurs, bonsoir, bienvenue, minutes, ...
3   [tout, bonsoir, toutes, tous, rendez, retrouve...
4   [merci, tout, dabord, davoir, répondu, appel, ...
5   [bienvenue, journal, lintelligence, économique...
6   [bienvenue, projet, maroc, chaîne, présente, a...
7   [bonjour, tout, monde, bienvenue, urgent, fait...
8   [comment, maroc, estil, devenu, e, puissance, ...
9   [bonjour, tout, monde, bienvenue, urgence, éco...
10  [bonjour, tous, bienvenue, projet, maroc, ravi...
11  [bonsoir, tous, bienvenue, linvité, rédaction,...
12  [applaudissements, alors, plaisir, lancer, auj...
13  [cette, émission, présentée, thème, wilcom, fe...
14  [bien, bonjour, toutes, tous, jespère, allez, ...
15  [bonjour, toutes, tous, bienvenue, grand, form...
16  [madame, monsieur, bonsoir, menu, questions, d...
17  [crise, ukraine, a, causé, première, fois, mar...
18  [comme, partout, ailleurs, monde, entreprises,...
19  [cette, émission, présentée, thème, wilcom, st...
20  [rapports, bakel, maghreb, statistiques, monét...
21  [si, limite, dit, textuellement, linstrument, ...
22  [si, limite, dit, textuellement, linstrument, ...
23  [lenvironnement, actuel, caractérisé, a, envie...
24  [investissements, directs, étrangers, plein, b...
25  [voilà, monsieur, bonsoir, menu, deux, questio...
26  [lafrique, point, vue, lintelligence, économiq...
27  [enchaînement, projets, économiques, unis, vis...
28  [malgré, renchérissement, prix, matières, prem...
29  [bonsoir, bienvenue, linvité, rédaction, medit...
30  [situé, entre, bassin, méditerranéen, locéan, ...
31  [fin, années, siècle, dernier, lancer, grand, ...
32  [lannée, sannonce, économiquement, difficile, ...
33  [deux, façades, maritimes, sans, littoral, res...
34  [tuation, économique, marocaine, vicky, bogaer...
35  [taux, dinflation, annuel, maroc, a, bondit, j...
36  [grâce, phosphate, fabrique, quon, appelle, en...
37  [a, réussi, choisir, casablanca, maroc, prépar...
38  [suisse, meurs, dispositif, économique, encour...
39  [bonjour, tous, propose, aujourdhui, petite, v...
40  [bienvenue, journal, lintelligence, économique...
41  [bonjour, tout, monde, bienvenue, urgence, éco...
42  [parmi, institutions, contribuent, développeme...
43  [bonjour, tout, monde, bienvenue, urgence, éco...
44  [maroc, resté, lordre, grandeur, grands, pays,...
45  [cette, conférence, diplomatie, économique, pe...
46  [bienvenue, chaîne, projet, maroc, aujourdhui,...
47  [bienvenue, chaîne, projet, maroc, aujourdhui,...
48  [cette, émission, présenté, caisse, centrale, ...
49  [bonjour, bonjour, alors, expert, domaine, log...
50  [bonjour, bienvenue, urgence, économique, alor...
51  [bienvenue, chaîne, projet, maroc, aujourdhui,...
52  [cette, émission, présentée, thème, wilcom, te...
53  [salam, tous, bienvenue, maroc, noubliez, abon...
54  [salam, tous, bienvenue, maroc, noubliez, abon...
55  [donc, résumé, lannée, vient, sécouler, maroc,...

In [37]:
df_expanded.to_csv('encoded_dataset.csv', index=False,encoding='utf-8')